name: CI
on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
              libasound2-dev \
              libudev-dev \
              libxcb-render0-dev \
              libxcb-shape0-dev \
              libxcb-xfixes0-dev
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: clippy, rustfmt
        - uses: Swatinem/rust-cache@v2
        - run: cargo test --all-features
        - run: cargo clippy --all-targets --all-features -- -D warnings
        - run: cargo fmt --check
        - run: cargo doc --no-deps

    compatibility:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
              libasound2-dev \
              libudev-dev \
              libxcb-render0-dev \
              libxcb-shape0-dev \
              libxcb-xfixes0-dev
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: clippy, rustfmt
        - uses: Swatinem/rust-cache@v2
        - run: cargo test
