name: CI
on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: cargo test --all-features
        - run: cargo clippy --all-targets --all-features -- -D warnings
        - run: cargo fmt --check
        - run: cargo doc --no-deps

    compatibility:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: cargo test
